### ISSUE TITLE
lazyraster crop is changing grid resolution

### ISSUE THREAD

**Issue by Blundys** [hypertidy/lazyraster#19]
Hi I am keen to use the lazyraster for some quicker processing when dealing with large grids that I don't need the whole extent. 
However, I found that when I use lazyraster::crop it is changing the grid resolution even if I use `native = TRUE` when converting it to a raster at the end.

I've created a very simple reprex to highlight

``` r
library(raster)
#> Loading required package: sp
library(lazyraster)
#> 
#> Attaching package: 'lazyraster'
#> The following object is masked from 'package:graphics':
#> 
#>     plot

dummycroparea <- extent(0.2,0.8,0.2,0.8)

r1 <- raster(matrix(1:25, nrow = 5), xmn=0, xmx=1, ymn=0, ymx=1, crs=NA, template=NULL)

writeRaster(r1, "C:/temp/dummyraster_sml.tif")

lr1 <- lazyraster("C:/temp/dummyraster_sml.tif")

r1_crop <-  raster::crop(r1, dummycroparea)
lr_crop <- lazyraster::crop(lr1, dummycroparea)

lr_crop_to_rast <- as_raster(lr_crop, native = TRUE)


res(r1_crop)
#> [1] 0.2 0.2
res(lr_crop_to_rast)
#> [1] 0.15 0.12

dim(r1_crop)
#> [1] 3 3 1
dim(lr_crop_to_rast)
#> [1] 5 4 1

values(r1_crop)
#> [1]  7 12 17  8 13 18  9 14 19
values(lr_crop_to_rast)
#>  [1]  6 11 16 21  7 12 17 22  8 13 18 23  9 14 19 24 10 15 20 25
```

<sup>Created on 2020-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdsumner** [comment]
oops, thank you quite right I will check that out

**Comment by mdsumner** [comment]
I think I fixed it ...

Thanks so much, hopefully you can get what you want now, appreciate the example it needed a clean up! 

To test

```R
remotes::install_github("hypertidy/lazyraster")
```

let me know

**Comment by mdsumner** [comment]
oh one note, when lazyraster does `crop()` it behaves as if you would have done `raster::crop(, , snap = "out")` because I always found that annoying that it wasn't the default. When I'm comparing output with raster, need to make sure to use that option

**Comment by Blundys** [comment]
Thanks for such a quick answer Mike, I may not have time to check until next week but will let you know if I'm still having an issue

**Comment by Blundys** [comment]
Hi Mike, I updated lazyraster (now lazyraster_0.5.0.9004) and I am still having this issue but I get a slightly different output to before.

If I run my example from before  my `dim(lr_crop_to_rast)` now give 5 5 1 (instead of 5 4 1) but values in the outmost corners are duplicated

```
as.matrix(r1_crop)
     [,1] [,2] [,3]
[1,]    7   12   17
[2,]    8   13   18
[3,]    9   14   19
as.matrix(lr_crop_to_rast)
     [,1] [,2] [,3] [,4] [,5]
[1,]    7    7   12   17   17
[2,]    7    7   12   17   17
[3,]    8    8   13   18   18
[4,]    9    9   14   19   19
[5,]    9    9   14   19   19
```

**Comment by mdsumner** [comment]
eek, thanks for following up - bit dismayed I have failed to get this right ...  as a workaround (now I think of it) `native = TRUE` would be equivalent to `raster::crop(raster(file), ex)`

**Comment by Blundys** [comment]
Hey I have `native = TRUE` in `lr_crop_to_rast <- as_raster(lr_crop, native = TRUE)` (in my example) is that where it is meant to be? It is still changing the resolution?

**Comment by mdsumner** [comment]
yes its, sadly I won't be able to fix for a while - you can workaround by just doing  `raster::crop(raster(file), ex)` - because, there's nothing for lazyraster to do in that case, it won't make any difference (but I will fix eventually)
